# NUMPY MODULE`
import numpy as n

In [24]:
import numpy as n
a1= numpy.array([12,123,4,5,6,77])

In [25]:

print(a1)

[ 12 123   4   5   6  77]


In [26]:
a1

array([ 12, 123,   4,   5,   6,  77])

In [27]:
type(a1)

numpy.ndarray

In [28]:
a1 = n.array([1,2,3,4,5,6,7,8,9,10])

In [29]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
type(a1)

numpy.ndarray

In [32]:
a2 = n.array([2,3.4,'nope'])

In [33]:
a2

array(['2', '3.4', 'nope'], dtype='<U32')

In [34]:
print(a2)

['2' '3.4' 'nope']


In [35]:
type(a2)

numpy.ndarray

In [36]:
%%timeit
a2 = n.array([2,3.4,'nope'])

3.11 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [37]:
a2.dtype

dtype('<U32')

In [38]:
a1.dtype

dtype('int32')

In [40]:
a2.shape 

(3,)

In [41]:
a2.ndim   #dimension of array

1

In [48]:
a1 = a1 + 15

In [49]:
a1[3:]

array([19, 20, 21, 22, 23, 24, 25])

# linear equations

In [50]:
x = n.array([1,2,3,4,5])

In [52]:
new1 = x + 3.4 + 12
new1

array([16.4, 17.4, 18.4, 19.4, 20.4])

In [53]:
print(new1)

[16.4 17.4 18.4 19.4 20.4]


In [55]:
n.arange(10)    #alike range functions

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
print(n)

<module 'numpy' from 'C:\\Users\\mihik\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>


In [58]:
n.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
n.arange(2)

array([0, 1])

In [62]:
a1 = n.arange(10)

In [63]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [65]:
n.arange(5,10)

array([5, 6, 7, 8, 9])

In [68]:
n.arange(-5,5,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [70]:
n.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
n.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [92]:
arr2d = n.array([[2,3,1] ,[2,3,1], [3,4,1], [3,4,5]])

In [93]:
print(arr2d)

[[2 3 1]
 [2 3 1]
 [3 4 1]
 [3 4 5]]


In [94]:
arr2d.shape

(4, 3)

In [95]:
arr2d.ndim

2

In [96]:
arr2d.flatten()

array([2, 3, 1, 2, 3, 1, 3, 4, 1, 3, 4, 5])

In [97]:
arr2d.flatten().shape

(12,)

In [98]:
arr2d.size

12

In [107]:
arr2d.reshape(2,
              -1)

array([[2, 3, 1, 2, 3, 1],
       [3, 4, 1, 3, 4, 5]])

In [108]:
arr2d.reshape(1,-1)

array([[2, 3, 1, 2, 3, 1, 3, 4, 1, 3, 4, 5]])

In [109]:
arr2d.reshape(4,-1)

array([[2, 3, 1],
       [2, 3, 1],
       [3, 4, 1],
       [3, 4, 5]])

In [102]:
arr2d.reshape(2,-1)

array([[2, 3, 1, 2, 3, 1],
       [3, 4, 1, 3, 4, 5]])

In [103]:
arr2d.reshape(3,-1)

array([[2, 3, 1, 2],
       [3, 1, 3, 4],
       [1, 3, 4, 5]])

In [105]:
arr2d.reshape(2,2,-1)

array([[[2, 3, 1],
        [2, 3, 1]],

       [[3, 4, 1],
        [3, 4, 5]]])

In [110]:
arr2d.reshape(2,2,-1).ndim

3

In [135]:
ar2d = n.array([[[10,11,12] ,[7,8,9]], [[4,5,6], [1,2,3]]])

In [136]:
print(ar2d)

[[[10 11 12]
  [ 7  8  9]]

 [[ 4  5  6]
  [ 1  2  3]]]


In [137]:
ar2d.ndim

3

In [138]:
ar2d[0][1][1]

8

In [139]:
ar2d[0:3]

array([[[10, 11, 12],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [ 1,  2,  3]]])

In [140]:
ar2d[0:3,0:1]

array([[[10, 11, 12]],

       [[ 4,  5,  6]]])

In [142]:
ar2d[0:2,0:1]

array([[[10, 11, 12]],

       [[ 4,  5,  6]]])

In [147]:
ar2d[1][0][1]

5

In [157]:
arr = n.array([1,-7,2,3,4,5,6])

In [158]:
n.unique(arr)

array([-7,  1,  2,  3,  4,  5,  6])

In [159]:
n.mean(arr)

2.0

In [160]:
n.max(arr)

6

In [161]:
n.min(arr)

-7

In [162]:
n.abs(arr)

array([1, 7, 2, 3, 4, 5, 6])

In [163]:
n.min(arr)

-7

In [164]:
n.histogram

<function numpy.histogram(a, bins=10, range=None, density=None, weights=None)>